version: "3.9"
services:
  postgres:
    container_name: simplebank-postgres
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simplebank
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    container_name: simplebank-api
    image: simplebank
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres:5432/simplebank?sslmode=disable
      - GIN_MODE=release
    depends_on:
      - postgres
#    links:
#      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ] # override entrypoint in Dockerfile, wait-for is cover links purpose
    command: [ "/app/main" ]
