services:
  postgres:
    container_name: simplebank-postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    networks:
      - simplebank-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simplebank

  redis:
    container_name: simplebank-redis
    image: redis:8-alpine
    ports:
      - "6379:6379"
    networks:
      - simplebank-net

  api:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    container_name: simplebank-api
    image: simplebank
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      - simplebank-net
    env_file:
      - app.env
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres:5432/simplebank?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - postgres
      - redis

    # entrypoint will override ENTRYPOINT in Dockerfile,
    # meaning that CMD will be ignored too
    entrypoint: [
      "/app/wait-for.sh", "postgres:5432", "--",
      "/app/start.sh"
    ]
    command: [ "/app/main" ]

networks:
  simplebank-net:
      name: simplebank-net
      external: false
