### Create a user
POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "username": "ymanshur",
  "full_name": "Yusuf Manshur",
  "email": "ymanshur@gmail.com",
  "password": "secret123"
}

### Create a account
POST http://localhost:8080/accounts
Accept: */*
Content-Type: application/json
Authorization: Bearer v2.local.HeqbB55KCrBW-TnIzKoeifpUND6ej_rsVEfnat8XSM2I8WRPGjGtnHh4JnQdDKu9jgJbZ0PtX-7vb500PpBlIRjseTbZmL8Qsv7lE2d_4k3qWO31I4lerf4PXB1zfMr6L_vthN657O-OV-6L6nrxADJ-ZLb2i0RPiLBQB6iNfC2akGjjPiwjJdM8boHrTzaxoLijbz2Fsq-lO0YtH7IK2_EREhkXPjLK9wcf45Tpwevswl-8Nu96GIzH0eRgrdLVyVf6GEv7SMj8mFSRnKWHrA.bnVsbA

{
  "currency": "USD"
}

### Get a account by id
GET http://localhost:8080/accounts/11
Accept: */*
Authorization: Bearer v2.local.HeqbB55KCrBW-TnIzKoeifpUND6ej_rsVEfnat8XSM2I8WRPGjGtnHh4JnQdDKu9jgJbZ0PtX-7vb500PpBlIRjseTbZmL8Qsv7lE2d_4k3qWO31I4lerf4PXB1zfMr6L_vthN657O-OV-6L6nrxADJ-ZLb2i0RPiLBQB6iNfC2akGjjPiwjJdM8boHrTzaxoLijbz2Fsq-lO0YtH7IK2_EREhkXPjLK9wcf45Tpwevswl-8Nu96GIzH0eRgrdLVyVf6GEv7SMj8mFSRnKWHrA.bnVsbA

### List accounts
GET http://localhost:8080/accounts?page_id=1&page_size=5
Accept: */*
Authorization: Bearer v2.local.HeqbB55KCrBW-TnIzKoeifpUND6ej_rsVEfnat8XSM2I8WRPGjGtnHh4JnQdDKu9jgJbZ0PtX-7vb500PpBlIRjseTbZmL8Qsv7lE2d_4k3qWO31I4lerf4PXB1zfMr6L_vthN657O-OV-6L6nrxADJ-ZLb2i0RPiLBQB6iNfC2akGjjPiwjJdM8boHrTzaxoLijbz2Fsq-lO0YtH7IK2_EREhkXPjLK9wcf45Tpwevswl-8Nu96GIzH0eRgrdLVyVf6GEv7SMj8mFSRnKWHrA.bnVsbA

### Transfer money
POST http://localhost:8080/transfers
Accept: */*
Content-Type: application/json
Authorization: Bearer v2.local.HeqbB55KCrBW-TnIzKoeifpUND6ej_rsVEfnat8XSM2I8WRPGjGtnHh4JnQdDKu9jgJbZ0PtX-7vb500PpBlIRjseTbZmL8Qsv7lE2d_4k3qWO31I4lerf4PXB1zfMr6L_vthN657O-OV-6L6nrxADJ-ZLb2i0RPiLBQB6iNfC2akGjjPiwjJdM8boHrTzaxoLijbz2Fsq-lO0YtH7IK2_EREhkXPjLK9wcf45Tpwevswl-8Nu96GIzH0eRgrdLVyVf6GEv7SMj8mFSRnKWHrA.bnVsbA

{
  "from_account_id": 4,
  "to_account_id": 1,
  "amount": 10,
  "currency": "USD"
}

### Login
POST http://localhost:8080/users/login
Accept: */*
Content-Type: application/json

{
  "username": "ymanshur",
  "password": "secret123"
}