### Create a user
POST http://{{authority}}/users HTTP/1.1
Accept: */*
Content-Type: application/json

{
  "username": "ymanshur",
  "full_name": "Yusuf Manshur",
  "email": "ymanshur@gmail.com",
  "password": "secret123"
}

### Create an account
POST http://{{authority}}/accounts
Accept: */*
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "currency": "USD"
}

### Get an account by id
GET http://{{authority}}/accounts/1
Accept: */*
Authorization: Bearer {{accessToken}}

### List accounts
GET http://{{authority}}/accounts
    ?page_id=1
    &page_size=5
Accept: */*
Authorization: Bearer {{accessToken}}

### Transfer money
POST http://{{authority}}/transfers
Accept: */*
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "from_account_id": 4,
  "to_account_id": 1,
  "amount": 10,
  "currency": "USD"
}

### Login user
POST http://{{authority}}/users/login
Accept: */*
Content-Type: application/json

{
  "username": "ymanshur",
  "password": "secret123"
}

### Renew access token
POST http://{{authority}}/tokens/renew_access
Accept: */*
Content-Type: application/json

{
  "refresh_token": "v2.local.Z-8U9DDUiDdsTM7sqezgbshmPcef8dio4t59NcdT14i0XFutvasl86Lj3tVgFsUsCdhpF1B8qOwbF4GE7uX96pQPAyhFmrJ85xSn3tetM8qLX4ieJ8Xrmmw__h_PtqprqP0DKbl8d5xH-xNtospa9WhuKikmenGOdI5z5Y7BHNwWaMtWJOHQz9-C8uUeGT62mdLaHXSRQZRxVRpMOTedfCH_O4xEpwbVya100HOfUNmkYbQ-fWki60Ff65MRGhfqdvIx97q-m44GTDR9oVSR.bnVsbA"
}