### Create a user
POST http://{{authority}}/api/users HTTP/1.1
Accept: */*
Content-Type: application/json

{
  "username": "ymanshur",
  "full_name": "Yusuf Manshur",
  "email": "ymanshur@gmail.com",
  "password": "secret123"
}

### Create an account
POST http://{{authority}}/api/accounts
Accept: */*
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "currency": "USD"
}

### Get an account by id
GET http://{{authority}}/api/accounts/1
Accept: */*
Authorization: Bearer {{accessToken}}

### List accounts
GET http://{{authority}}/api/accounts
    ?page_id=1
    &page_size=5
Accept: */*
Authorization: Bearer {{accessToken}}

### Transfer money
POST http://{{authority}}/api/transfers
Accept: */*
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "from_account_id": 4,
  "to_account_id": 1,
  "amount": 10,
  "currency": "USD"
}

### Login user
POST http://{{authority}}/api/login_user
Accept: */*
Content-Type: application/json

{
  "username": "ymanshur",
  "password": "secret123"
}

### Renew access token
POST http://{{authority}}/api/renew_access_token
Accept: */*
Content-Type: application/json

{
  "refresh_token": {{refreshToken}}
}
